In [1]:

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
def load_data(file_path):
    return pd.read_csv(file_path)

df = load_data(file_path="../Data/raw/loan_approval_dataset.csv")
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [3]:
# Create a Working Copy

df_clean = df.copy()
df_clean.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [4]:
# Standardize Column Names

print(df_clean.columns.tolist())

# Standardize column names

df_clean.columns = (df_clean.columns.str.strip().str.lower().str.replace(" ", "_"))
print(df_clean.columns.to_list())

['loan_id', ' no_of_dependents', ' education', ' self_employed', ' income_annum', ' loan_amount', ' loan_term', ' cibil_score', ' residential_assets_value', ' commercial_assets_value', ' luxury_assets_value', ' bank_asset_value', ' loan_status']
['loan_id', 'no_of_dependents', 'education', 'self_employed', 'income_annum', 'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value', 'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value', 'loan_status']

In [5]:
# Check Missing Values

df_clean.isnull().sum()

# Better Business View

missing_values = pd.DataFrame({
    "Missing Values": df_clean.isnull().sum(),
    "Percentage": (df_clean.isnull().sum() / len(df_clean)) * 100
})

missing_values

# Sort by Missing Values

missing_values = missing_values.sort_values(
    by="Missing Values",
    ascending=False
)

missing_values

                          Missing Values  Percentage
loan_id                                0         0.0
no_of_dependents                       0         0.0
education                              0         0.0
self_employed                          0         0.0
income_annum                           0         0.0
loan_amount                            0         0.0
loan_term                              0         0.0
cibil_score                            0         0.0
residential_assets_value               0         0.0
commercial_assets_value                0         0.0
luxury_assets_value                    0         0.0
bank_asset_value                       0         0.0
loan_status                            0         0.0

In [6]:
# Duplicate Record Analysis

duplicates = df_clean[df_clean.duplicated()]
duplicates

# Duplicates Found
# df_clean.drop_duplicates(inplace=True)

Empty DataFrame
Columns: [loan_id, no_of_dependents, education, self_employed, income_annum, loan_amount, loan_term, cibil_score, residential_assets_value, commercial_assets_value, luxury_assets_value, bank_asset_value, loan_status]
Index: []

In [7]:
# Check for Extra Spaces in Categorical Values

categorical_columns = df_clean.select_dtypes(include="object").columns
print(categorical_columns)

for col in categorical_columns:
    print("=" * 50)
    print(col)
    print(df_clean[col].unique())

Index(['education', 'self_employed', 'loan_status'], dtype='str')
==================================================
education
<StringArray>
[' Graduate', ' Not Graduate']
Length: 2, dtype: str
==================================================
self_employed
<StringArray>
[' No', ' Yes']
Length: 2, dtype: str
==================================================
loan_status
<StringArray>
[' Approved', ' Rejected']
Length: 2, dtype: str

In [8]:
# If Extra Spaces Exist

for col in categorical_columns:
    df_clean[col] = df_clean[col].str.strip()

for col in categorical_columns:
    print("=" * 50)
    print(col)
    print(df_clean[col].unique())

==================================================
education
<StringArray>
['Graduate', 'Not Graduate']
Length: 2, dtype: str
==================================================
self_employed
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
==================================================
loan_status
<StringArray>
['Approved', 'Rejected']
Length: 2, dtype: str

In [9]:
# Check Constant Columns

constant_columns = []

for col in df_clean.columns:
    if df_clean[col].nunique() == 1:
        constant_columns.append(col)

print(constant_columns)


# If Constant Columns Exist
# df_clean.drop(columns=constant_columns, inplace=True)

[]

In [10]:
# Check Invalid Values
# Now inspect each column for unrealistic values.

df_clean.describe().T

,count,mean,std,min,25%,50%,75%,max
loan_id,4269.0,2.135000e+03,1.232498e+03,1.0,1068.0,2135.0,3202.0,4269.0
no_of_dependents,4269.0,2.498712e+00,1.695910e+00,0.0,1.0,3.0,4.0,5.0
income_annum,4269.0,5.059124e+06,2.806840e+06,200000.0,2700000.0,5100000.0,7500000.0,9900000.0
loan_amount,4269.0,1.513345e+07,9.043363e+06,300000.0,7700000.0,14500000.0,21500000.0,39500000.0
loan_term,4269.0,1.090045e+01,5.709187e+00,2.0,6.0,10.0,16.0,20.0
cibil_score,4269.0,5.999361e+02,1.724304e+02,300.0,453.0,600.0,748.0,900.0
residential_assets_value,4269.0,7.472617e+06,6.503637e+06,-100000.0,2200000.0,5600000.0,11300000.0,29100000.0
commercial_assets_value,4269.0,4.973155e+06,4.388966e+06,0.0,1300000.0,3700000.0,7600000.0,19400000.0
luxury_assets_value,4269.0,1.512631e+07,9.103754e+06,300000.0,7500000.0,14600000.0,21700000.0,39200000.0
bank_asset_value,4269.0,4.976692e+06,3.250185e+06,0.0,2300000.0,4600000.0,7100000.0,14700000.0

In [11]:
(df_clean["residential_assets_value"] < 0).sum()

np.int64(28)

In [12]:
# Save the Clean Dataset

df_clean.to_csv("../data/processed/loan_approval_dataset_cleaned.csv",index=False)

In [13]:
df_clean.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected